/* build/Linux-framebuffer/testament.h
 * 
 * Revision testament.
 *
 * *WARNING* this file is automatically generated by git-testament.pl 
 *
 * Copyright 2012 NetSurf Browser Project
 */

#ifndef NETSURF_REVISION_TESTAMENT
#define NETSURF_REVISION_TESTAMENT "fc6f2dab6fa9b8e28ec326aa551b9ccd"

/* Revision testament checksum:
 * MD5:fc6f2dab6fa9b8e28ec326aa551b9ccd
 */

/* Revision testament: */
#define USERNAME "jam"
#define GECOS "Jonas A"
#define WT_ROOT "/usr/jam/dev-netsurf/workspace/netsurf/"
#define WT_HOSTNAME "clay"
#define WT_COMPILEDATE "03.08.2019"
#define WT_BRANCHPATH "master"
#define WT_BRANCHISMASTER 1
#define WT_REVID "e01bbee4056786d08fbaf8f347fa17033a8f3e62"
#define WT_MODIFIED 21
#define WT_MODIFICATIONS {\
  { "deb_nsfb.txt", "??" }, \
  { "utils/utf8.c", " M" } \
}

#endif
